version: 0.0
Resources:

 - TargetService:
    Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:$accountId:task-definition/springdemo:$taskVer"
        LoadBalancerInfo:
          ContainerName: "springdemo"
          ContainerPort: 80

Hooks:
  - AfterAllowTestTraffic: "AfterAllowTestTraffic"
