version: 0.1

phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - javac --version 
      - java --version
      - mvn clean package
      - echo Build Ended on `date`

  post_build:
    commands:
      - echo bucket name is $BUCKET_NAME
      - cp target/springdemo2-1.0.0-SNAPSHOT.jar codedeploy 
      - ls -lrt codedeploy
      - cd codedeploy && zip -r ../springdemo2.zip * 
      - ls -lrt springdemo2.zip
artifacts:
  files:
    - springdemo2.zip
  discard-paths: yes
