version: 0.1

phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - yum install -y wget unzip zip jq mysql ansible
      - echo before install 
      - java --version 
      - javac --version 
      - wget https://download.java.net/java/GA/jdk18/43f95e8614114aeaa8e8a5fcf20a682d/36/GPL/openjdk-18_linux-x64_bin.tar.gz -P /tmp
      - tar xzf /tmp/openjdk-18_linux-x64_bin.tar.gz -C /opt
      - rm -rf /tmp/openjdk-18_linux-x64_bin.tar.gz
      - alternatives --install /usr/bin/java java /opt/jdk-18/bin/java 2
      - alternatives --install /usr/bin/javac javac /opt/jdk-18/bin/javac 2

  build:
    commands:
      - echo Build started on `date`
      - javac --version 
      - java --version
      - mvn clean package
      - echo Build Ended on `date`

  post_build:
    commands:
      - echo bucket name is $BUCKET_NAME
      - cp target/springdemo2-1.0.0-SNAPSHOT.jar codedeploy 
      - ls -lrt codedeploy
      - cd codedeploy && zip -r ../springdemo2.zip * 
      - ls -lrt springdemo2.zip
artifacts:
  files:
    - springdemo2.zip
  discard-paths: yes
