version: 0.2

env: 
   variables: 
     MSG: "hello from runner2" 

   secrets-manager: 
     MYSQL_ENDPOINT: "db_creds/mysql_endpoint"

phases:

#  build:
#    commands:
#      - mvn clean package
#      - echo Build Ended on `date`
#
  post_build:
    commands:
      - rm -rf src/test
      - ls -lrt src 
      - echo removed src/test 
      - echo message from codebuild $MSG 
      - echo endpoint $MYSQL_ENDPOINT 
      #- cp target/springdemo2-1.0.0-SNAPSHOT.jar codedeploy 
artifacts:
  files:
    - '**/*'
  base-directory: src 
  discard-paths: false  
