version: 0.2

env: 
   variables: 
     MSG: "hello from runner2" 

   secrets-manager: 
     MYSQL_ENDPOINT: "db_creds:mysql_endpoint"

   parameter-store: 
     CIDR: "/dev/network/vpc_cidr" 

phases:

  build:
    commands:
      - mvn clean package
      - echo Build Ended on `date`

  post_build:
    commands:
      - echo message from codebuild $MSG 
      - echo endpoint $MYSQL_ENDPOINT 
      - echo my cidr block is $CIDR

      - cp target/springdemo2-1.0.0-SNAPSHOT.jar codedeploy 
artifacts:
  files:
    - '**/*'
  base-directory: cedeploy 
  discard-paths: false  
