version: 0.2

#phases:

#  build:
#    commands:
#      - mvn clean package
#      - echo Build Ended on `date`
#
#  post_build:
#    commands:
#      - rm -rf src/test
      #- cp target/springdemo2-1.0.0-SNAPSHOT.jar codedeploy 
artifacts:
  files:
    - '**/*'
  base-directory: src 
  discard-paths: false  
