version: 0.0
os: linux
files:
  - source: springdemo2-1.0.0.jar
    destination: /tmp
  - source: Dockerfile
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  #
  AfterInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root 
