version: 0.0
os: linux
files:
  - source: springdemo2-1.0.0.jar
    destination: /tmp
  - source: Dockerfile
    destination: /tmp
hooks:
  # stop any running containers 
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
      
  # Start application 
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  
  # Cleanup tasks goes here  
  ValidateService:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root 
