version: 0.0
Resources:

    # Pre-Requisites:
    # - Network is setup
    # 
    # - Target ECS service should have been created  
    # 
    - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:992382552000:task-definition/springdemo:1"
        LoadBalancerInfo:
          ContainerName: "springdemo"
          ContainerPort: 80

        # Optional properties
        #PlatformVersion: "LATEST"
        #NetworkConfiguration:
        #  AwsvpcConfiguration:
        #    Subnets: ["subnet-1234abcd","subnet-5678abcd"]
        #    SecurityGroups: ["sg-12345678"]
        #    AssignPublicIp: "DISABLED"
        #CapacityProviderStrategy:
          #- Base: 1
          #  CapacityProvider: "FARGATE_SPOT"
          #  Weight: 2
        #  - Base: 0
        #    CapacityProvider: "FARGATE"
        #    Weight: 1
Hooks:
  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
  - AfterAllowTestTraffic: "LambdaFunctionToValidateAfterTestTrafficStarts"
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"