version: 0.0
Resources:

    # Pre-Requisites:
    # - Network is setup
    # 
    # - Target ECS service should have been created  
    # 
    - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: TASKDEF_ARN
        LoadBalancerInfo:
          ContainerName: "springdemo"
          ContainerPort: 80

Hooks:
   - AfterAllowTestTraffic: "AfterAllowTestTraffic"

#  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
#  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
#  - AfterAllowTraffic: "ductionTraffic"
