version: 0.0
os: linux
files:
  - source: springdemo2-1.0.0-SNAPSHOT.jar
    destination: /tmp
  - source: Dockerfile
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  SomeStuffIDo: "echo inside stuff"
  OtherThings: "ls -lrt" 
  NewOne: 
    - "echo newone"
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
